Manage Authors names and Bio from GitHub issues in the repository
basilkhan05/bookstore-client pull request #1
Opened 2019-01-14 13:04 UTC by basilkhan05

## This feature allows the Author's `biography` to be updated from Github Issues
- Templates to include `biography` when viewing authors

## Additional Features
- Thank You message when the user clicks on "Purchase Book for"
- Cancel/Close button on both dialog boxes
- Update README Documentation with setup instructions

## Assumptions
- As per the tutorial, we will assume authors rarely publish books and background reloads will only be needed every hour

2019-01-16 10:27 UTC, vladucu requested changes
Looks good overall, Basil!

Thanks for all the details in the description of the PR. Only one small enhancement suggestion from me.

2019-01-16 10:27 UTC, vladucu commented on app/components/book-cover.js
> +      this.set('isShowingPurchaseModal', false);
in cases like here, where you're setting 2 properties on the same object (`this` here), it's best to use `setProperties`, ex:
```js
this.setProperties({
  isShowingPurchaseModal: false,
  isShowingThankYouModal: true
});
```

2019-01-17 13:07 UTC, basilkhan05 commented on app/components/book-cover.js
> +      this.set('isShowingPurchaseModal', false);
Thanks Vlad! I have refactored this section and pushed to the branch.

2019-01-17 13:57 UTC, vladucu approved these changes
Sweet!! Thanks for updating with the suggestion in the other place too!

This looks pretty good to me, Basil. Let's merge this 🎉

2019-01-22 14:57 UTC, merged

2019-01-22 16:30 UTC, vladucu commented
🎉